const mongoose=require('mongoose')
const productSchema=new mongoose.Schema({
    name:{
        type:String,
        required:true
    },
    brand:{
        type:String,
        required:true
    },
    category:{
        type:String,
        required:true
    },
    price:{
        type:String,
        required:true
    },
    stock:{
        type:Number,
        required:true
    },
    images:{
        type:[String],
        required:true
    },
    shades:[{
        color:{
            type:String,
            required:true
        },
        name:{
            type:String,
            required:true
        }
    }],
    description:{
        type:String
    }
})

module.exports=mongoose.model('product',productSchema)